name: PHP Code Style

on:
  push:
    paths:
      - '**.php'

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          extensions: rdkafka

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPCs
        run: ./vendor/bin/php-cs-fixer fix --config .php-cs-fixer.php --dry-run
